version: '3'
services:
  web:
    image: l00187929/heart_risk:1.0  # ✅ Use the exact tag you pushed
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure


