apiVersion: v1
kind: Service
metadata:
  name: heart-risk
spec:
  selector:
    app: heart-app
  ports:
    - protocol: TCP
      port: 80            # Expose service on port 80
      targetPort: 5000    # Forward to container port 5000
  type: NodePort         # To access externally on a Node port
